name: Scrape Browns Roster Automation

on:
  push:
    branches:
      - scraper
  schedule:
    - cron: "0 3 * * *" # Runs at 03:00 AM (UTC) every day (Check https://crontab.guru/)

jobs:
  scrape-browns-roster-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: 🚀 Run Automation
        run: node scraper.js
